spring:
    application:
        name: library-management-v2

    datasource:
        url: jdbc:postgresql://localhost:5432/spring_mvc_lib_mang_v2
        username: postgres
        password: P@SSW0RDs3003
        driver-class-name: org.postgresql.Driver

        hikari:
            auto-commit: false

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        properties:
            hibernate:
                connection:
                    provider_disables_autocommit: true

jwt:
    secret: Qt20iylRG7UFc5wjL7u8wFQovTOlS8A1/DK8Mq6HqRU=
    expiration: 3600000 # 1hour in milliseconds