package com.sudhanva.library_management_v2.enums.Error;

public enum ErrorCode {

    // Member
    MEMBER_NOT_FOUND,
    MEMBER_INACTIVE,
    MEMBER_EMAIL_ALREADY_EXISTS,
    MEMBER_HAS_ACTIVE_BORROWS,

    // Book
    BOOK_NOT_FOUND,
    BOOK_INACTIVE,
    BOOK_NOT_AVAILABLE,
    BOOK_ALREADY_EXISTS,
    BOOK_ISBN_ALREADY_EXISTS,
    INVALID_BOOK_COPIES,
    BOOK_CURRENTLY_BORROWED,

    // Borrow Transaction
    BORROW_TRANSACTION_NOT_FOUND,
    NO_BORROW_TRANSACTIONS_FOUND,
    MAX_BOOK_LIMIT_EXCEEDED,
    DUPLICATE_BOOK_REQUEST,
    BOOK_ALREADY_BORROWED_BY_MEMBER,

    // Borrow Record / Return
    BORROW_RECORD_NOT_FOUND,
    NO_BORROW_RECORDS_FOUND,
    NO_UNRETURNED_BOOKS_FOUND,
    NO_ACTIVE_BORROWED_BOOKS,
    BOOK_NOT_BORROWED_BY_MEMBER,
    INVALID_RETURN_DATE,

    // Library Settings
    NO_LIBRARY_SETTINGS_AVAILABLE,
    SETTING_NOT_FOUND,
    INVALID_SETTING_VALUE,
    SETTING_ALREADY_EXISTS,

    // Auth
    PASSWORD_AND_CONFIRM_PASSWORD_DOESNT_MATCH,
    USER_EMAIL_ALREADY_EXISTS,
    USERNAME_ALREADY_EXISTS_EXCEPTION,
    UNAUTHORIZED,
    FORBIDDEN,
    INVALID_STAFF_ROLE,

    // Auth - Refresh Token
    NO_REFRESH_TOKEN_EXISTS,
    NOT_REFRESH_TOKEN,
    NO_REFRESH_TOKEN_RECORD_EXISTS,
    TOKEN_REVOKED,
    TOKEN_EXPIRED,
    TOKEN_SUBJECT_MISMATCH,
    INVALID_REFRESH_TOKEN,

    // Generic
    VALIDATION_FAILED,
    INTERNAL_SERVER_ERROR
}