spring.application.name=server2


spring.datasource.url=jdbc:postgresql://localhost:5432/tk_springmvc
spring.datasource.username=postgres
spring.datasource.password=P@SSW0RDs3003
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true